service: cotd-api

plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: ${env:DOMAIN}
    basePath: ""
    stage: ${self:provider.stage}
    createRoute53Record: true
  myStage: ${opt:stage, self:provider.stage}
  tableName: "cotd-api-${self:custom.myStage}"

package:
  exclude:
    - node_modules/**
    - .idea/**
    - .requirements/**
    - env/**
    - README.md
    - package.json
    - package-lock.json
    - requirements.txt

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  stage: main
  apiKeys:
    - COTD-API-KEY
  environment:
    DYNAMODB_TABLE: ${self:custom.tableName}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeTable
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  cotd:
    handler: cotd.index.handler
    events:
      # Get one
      - http:
          path: user/{user_id}/cotd/{cotd_id}
          method: GET
          cors: true
      # Get all
      - http:
          path: user/{user_id}/cotd
          method: GET
          cors: true
      # Create one
      - http:
          path: user/{user_id}/cotd
          method: post
          cors: true
      # Update one
      - http:
          path: user/{user_id}/cotd/{cotd_id}
          method: put
          cors: true
      # Delete one
      - http:
          path: user/{user_id}/cotd/{cotd_id}
          method: delete
          cors: true

resources:
  Resources:
    cotdsDynamoDbTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Delete
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: user_id
            AttributeType: S
          - AttributeName: cotd_id
            AttributeType: S
        KeySchema:
          - AttributeName: user_id
            KeyType: HASH
          - AttributeName: cotd_id
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
